// =============================================================================
// FILE    : bsp/s32k566/startup/startup_s32k566.cpp
// PURPOSE : Minimal Cortex-M7 startup for S32K566.
//           - Vector table with all exception and IRQ handlers
//           - Reset handler: copy .data, zero .bss, call SystemInit then main()
//
// NOTE: In a production project, use the startup file generated by NXP's
//       S32K5 SDK / RTD tool chain.  This file provides the minimum needed
//       to boot the CAN application in a bare-metal or VDK environment.
// =============================================================================

#include <cstdint>
#include <cstring>

// =============================================================================
// Symbols exported by the linker script
// =============================================================================
extern uint32_t __data_load_start;   // LMA of .data in Flash/MRAM
extern uint32_t __data_start;        // VMA start of .data in SRAM
extern uint32_t __data_end;          // VMA end   of .data in SRAM
extern uint32_t __bss_start;         // Start of .bss in SRAM
extern uint32_t __bss_end;           // End   of .bss in SRAM
extern uint32_t __stack_top;         // Top of main stack

// =============================================================================
// Forward declarations of the functions we need at compile time
// =============================================================================
extern "C" {
    int  main(void);
    void SystemInit(void);   // defined in system_s32k566.cpp

    // Default handler — loops forever, easy to catch in debugger
    void DefaultIRQHandler(void)   __attribute__((weak));
    void DefaultNMIHandler(void)   __attribute__((weak, alias("DefaultIRQHandler")));
    void HardFault_Handler(void)   __attribute__((weak, alias("DefaultIRQHandler")));
    void MemManage_Handler(void)   __attribute__((weak, alias("DefaultIRQHandler")));
    void BusFault_Handler(void)    __attribute__((weak, alias("DefaultIRQHandler")));
    void UsageFault_Handler(void)  __attribute__((weak, alias("DefaultIRQHandler")));
    void SVC_Handler(void)         __attribute__((weak, alias("DefaultIRQHandler")));
    void PendSV_Handler(void)      __attribute__((weak, alias("DefaultIRQHandler")));
    void SysTick_Handler(void)     __attribute__((weak, alias("DefaultIRQHandler")));

    // FlexCAN0 IRQ handlers — weak aliases so the BSP driver can override
    void FlexCAN0_Error_IRQHandler(void)    __attribute__((weak, alias("DefaultIRQHandler")));
    void FlexCAN0_BusOff_IRQHandler(void)   __attribute__((weak, alias("DefaultIRQHandler")));
    void FlexCAN0_ORed_0_15_MB_IRQHandler(void) __attribute__((weak, alias("DefaultIRQHandler")));
    void FlexCAN0_ORed_16_31_MB_IRQHandler(void)__attribute__((weak, alias("DefaultIRQHandler")));
}

// =============================================================================
// Reset handler — entry point from hardware
// =============================================================================
extern "C" void Reset_Handler(void) {
    // 1. Copy initialised data from Flash/MRAM → SRAM
    uint32_t* src = &__data_load_start;
    uint32_t* dst = &__data_start;
    while (dst < &__data_end) {
        *dst++ = *src++;
    }

    // 2. Zero-initialise BSS
    dst = &__bss_start;
    while (dst < &__bss_end) {
        *dst++ = 0U;
    }

    // 3. Platform / PLL / clock init (weak no-op if not provided)
    SystemInit();

    // 4. Call application main
    (void)main();

    // Should never return
    for (;;) {}
}

// =============================================================================
// Default IRQ handler — infinite loop
// =============================================================================
void DefaultIRQHandler(void) {
    for (;;) {}
}

// =============================================================================
// Vector table — placed in .isr_vector section (linker maps to 0x00400000)
//
// S32K566 has 240 external interrupts.  Only the most relevant ones are named
// below; the rest use the DefaultIRQHandler alias via the weak attribute.
//
// IRQ 109 = FlexCAN0_ORed_0_15_MB  (message buffers 0-15)
// IRQ 110 = FlexCAN0_ORed_16_31_MB (message buffers 16-31)
// IRQ 108 = FlexCAN0_Error
// IRQ 107 = FlexCAN0_BusOff
// =============================================================================
typedef void (*VectorEntry)(void);

__attribute__((section(".isr_vector"), used))
static VectorEntry const g_vectorTable[] = {
    // Arm Cortex-M7 system exceptions (offsets 0x00 – 0x3C)
    reinterpret_cast<VectorEntry>(&__stack_top),  // Initial stack pointer
    Reset_Handler,          // Reset
    DefaultNMIHandler,      // NMI
    HardFault_Handler,      // Hard fault
    MemManage_Handler,      // MPU fault
    BusFault_Handler,       // Bus fault
    UsageFault_Handler,     // Usage fault
    nullptr,                // Reserved
    nullptr,                // Reserved
    nullptr,                // Reserved
    nullptr,                // Reserved
    SVC_Handler,            // SVCall
    nullptr,                // Debug monitor (reserved)
    nullptr,                // Reserved
    PendSV_Handler,         // PendSV
    SysTick_Handler,        // SysTick

    // ---- External IRQs 0..119 (pad unused with DefaultIRQHandler) ----
    // IRQ 0-106: DefaultIRQHandler
    DefaultIRQHandler,  //   0
    DefaultIRQHandler,  //   1
    DefaultIRQHandler,  //   2
    DefaultIRQHandler,  //   3
    DefaultIRQHandler,  //   4
    DefaultIRQHandler,  //   5
    DefaultIRQHandler,  //   6
    DefaultIRQHandler,  //   7
    DefaultIRQHandler,  //   8
    DefaultIRQHandler,  //   9
    DefaultIRQHandler,  //  10
    DefaultIRQHandler,  //  11
    DefaultIRQHandler,  //  12
    DefaultIRQHandler,  //  13
    DefaultIRQHandler,  //  14
    DefaultIRQHandler,  //  15
    DefaultIRQHandler,  //  16
    DefaultIRQHandler,  //  17
    DefaultIRQHandler,  //  18
    DefaultIRQHandler,  //  19
    DefaultIRQHandler,  //  20
    DefaultIRQHandler,  //  21
    DefaultIRQHandler,  //  22
    DefaultIRQHandler,  //  23
    DefaultIRQHandler,  //  24
    DefaultIRQHandler,  //  25
    DefaultIRQHandler,  //  26
    DefaultIRQHandler,  //  27
    DefaultIRQHandler,  //  28
    DefaultIRQHandler,  //  29
    DefaultIRQHandler,  //  30
    DefaultIRQHandler,  //  31
    DefaultIRQHandler,  //  32
    DefaultIRQHandler,  //  33
    DefaultIRQHandler,  //  34
    DefaultIRQHandler,  //  35
    DefaultIRQHandler,  //  36
    DefaultIRQHandler,  //  37
    DefaultIRQHandler,  //  38
    DefaultIRQHandler,  //  39
    DefaultIRQHandler,  //  40
    DefaultIRQHandler,  //  41
    DefaultIRQHandler,  //  42
    DefaultIRQHandler,  //  43
    DefaultIRQHandler,  //  44
    DefaultIRQHandler,  //  45
    DefaultIRQHandler,  //  46
    DefaultIRQHandler,  //  47
    DefaultIRQHandler,  //  48
    DefaultIRQHandler,  //  49
    DefaultIRQHandler,  //  50
    DefaultIRQHandler,  //  51
    DefaultIRQHandler,  //  52
    DefaultIRQHandler,  //  53
    DefaultIRQHandler,  //  54
    DefaultIRQHandler,  //  55
    DefaultIRQHandler,  //  56
    DefaultIRQHandler,  //  57
    DefaultIRQHandler,  //  58
    DefaultIRQHandler,  //  59
    DefaultIRQHandler,  //  60
    DefaultIRQHandler,  //  61
    DefaultIRQHandler,  //  62
    DefaultIRQHandler,  //  63
    DefaultIRQHandler,  //  64
    DefaultIRQHandler,  //  65
    DefaultIRQHandler,  //  66
    DefaultIRQHandler,  //  67
    DefaultIRQHandler,  //  68
    DefaultIRQHandler,  //  69
    DefaultIRQHandler,  //  70
    DefaultIRQHandler,  //  71
    DefaultIRQHandler,  //  72
    DefaultIRQHandler,  //  73
    DefaultIRQHandler,  //  74
    DefaultIRQHandler,  //  75
    DefaultIRQHandler,  //  76
    DefaultIRQHandler,  //  77
    DefaultIRQHandler,  //  78
    DefaultIRQHandler,  //  79
    DefaultIRQHandler,  //  80
    DefaultIRQHandler,  //  81
    DefaultIRQHandler,  //  82
    DefaultIRQHandler,  //  83
    DefaultIRQHandler,  //  84
    DefaultIRQHandler,  //  85
    DefaultIRQHandler,  //  86
    DefaultIRQHandler,  //  87
    DefaultIRQHandler,  //  88
    DefaultIRQHandler,  //  89
    DefaultIRQHandler,  //  90
    DefaultIRQHandler,  //  91
    DefaultIRQHandler,  //  92
    DefaultIRQHandler,  //  93
    DefaultIRQHandler,  //  94
    DefaultIRQHandler,  //  95
    DefaultIRQHandler,  //  96
    DefaultIRQHandler,  //  97
    DefaultIRQHandler,  //  98
    DefaultIRQHandler,  //  99
    DefaultIRQHandler,  // 100
    DefaultIRQHandler,  // 101
    DefaultIRQHandler,  // 102
    DefaultIRQHandler,  // 103
    DefaultIRQHandler,  // 104
    DefaultIRQHandler,  // 105
    DefaultIRQHandler,  // 106
    DefaultIRQHandler,  // 107 FlexCAN0_BusOff (override with driver)
    FlexCAN0_Error_IRQHandler,       // 108 FlexCAN0_Error
    FlexCAN0_ORed_0_15_MB_IRQHandler,// 109 FlexCAN0 MB 0-15
    FlexCAN0_ORed_16_31_MB_IRQHandler,// 110 FlexCAN0 MB 16-31
    DefaultIRQHandler,  // 111
    DefaultIRQHandler,  // 112
    DefaultIRQHandler,  // 113
    DefaultIRQHandler,  // 114
    DefaultIRQHandler,  // 115
    DefaultIRQHandler,  // 116
    DefaultIRQHandler,  // 117
    DefaultIRQHandler,  // 118
    DefaultIRQHandler,  // 119
};
